### ISSUE TITLE
Embed Page

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#99]
So we want to have this page http://54.68.164.199:8083/ directly on the website - not separately.

Please copy the HTML and make it look somewhat decently. 

It should easily explain to developers what parameters can be use how. Provide 1-2 exmaple code snippets.

**Comment by kordianbruck** [comment]
Looks great. Can we please get some sample data into the map widget @Binabiko

**Comment by joern-vh** [comment]
I've been looking for - fix this by today I guess.

**Comment by chaoran-chen** [comment]
Done in #120.

**Comment by kordianbruck** [comment]
No, we are still missing the sample data in the map widget @chaoran-chen

**Comment by joern-vh** [comment]
Will be done by this evening @kordianbruck.

**Comment by joern-vh** [comment]
Closed by #125.
